intel-retail/automated-vending

docker-compose.ac.yml

fix: ms-inventory can not be read_only system

---

docker-compose.ac.yml
ds-card-reader/res/configuration.toml

fix: ds-card-reader messagequeue issue

---

docs/index.html
docs_src/index.md

docs: updated Ubuntu version to 20.04

---

ds-card-reader/common/common.go
ds-card-reader/device/config.go
ds-card-reader/device/config_test.go
ds-card-reader/device/physical.go
ds-card-reader/device/virtual_test.go
ds-card-reader/driver/driver.go
ds-card-reader/driver/driver_test.go
ds-card-reader/go.mod
ds-card-reader/go.sum
ds-card-reader/res/configuration.toml

Added custom configuration that closes #25

feat: Added custom config to ds-card-reader

---

ms-authentication/go.mod
ms-authentication/main.go
ms-authentication/routes/controller.go
ms-authentication/routes/controller_test.go
ms-authentication/routes/gets.go
ms-authentication/routes/gets_test.go

Partial Closes:#10
Closes:#15
Signed-off-by: intel <joshua.silverio@intel.com>

fix: refactor ms-authentication to use logging client to log errors/info

---

ms-inventory/go.mod
ms-inventory/main.go
ms-inventory/routes/common.go
ms-inventory/routes/common_test.go
ms-inventory/routes/controller.go
ms-inventory/routes/controller_test.go
ms-inventory/routes/deletes.go
ms-inventory/routes/deletes_test.go
ms-inventory/routes/gets.go
ms-inventory/routes/gets_test.go
ms-inventory/routes/sets.go
ms-inventory/routes/sets_test.go

Partial Closes:#10
Partial Closes:#15
Signed-off-by: intel <joshua.silverio@intel.com>

fix: refactor ms-inventory to use logging client to log errors/info 

---

ds-controller-board/device/config.go
ds-controller-board/device/config_test.go
ds-controller-board/device/device.go
ds-controller-board/device/physical.go
ds-controller-board/device/virtual.go
ds-controller-board/device/virtual_test.go
ds-controller-board/res/configuration.toml
ds-controller-board/res/devices/device-list.toml

changed device name in devices list to controller-board

fix: change device name in devices list to controller-board

---

ms-ledger/go.sum
ms-ledger/routes/deletes.go
ms-ledger/routes/gets.go
ms-ledger/routes/sets.go

feat: add more logging to ms-ledger functions

---

docker-compose.ac.yml
ms-inventory/Dockerfile
ms-inventory/main.go
ms-inventory/res/configuration.toml
ms-inventory/routes/common.go
ms-inventory/routes/common_test.go
ms-inventory/routes/controller.go

fix: moved inventory.json and auditlog.json file to use volumes

---

ms-inventory/main.go

error messages were written in correctly. this PR resolves this

fix: corrected error messages in main ms-inventory

---

as-controller-board-status/routes/controller.go
as-vending/routes/controller.go
ms-authentication/routes/gets.go
ms-inventory/main.go
ms-inventory/routes/deletes.go
ms-inventory/routes/gets.go
ms-inventory/routes/sets.go
ms-ledger/go.sum
ms-ledger/routes/deletes.go
ms-ledger/routes/gets.go
ms-ledger/routes/sets.go

feat: eliminate utilities.ProcessCORS and fix compile error

---

ms-inventory/routes/common_test.go
ms-inventory/routes/deletes_test.go
ms-inventory/routes/gets_test.go
ms-inventory/routes/sets_test.go

fix: ms-inventory unit test

---

as-controller-board-status/config/configuration.go
as-controller-board-status/functions/common.go
as-controller-board-status/functions/common_test.go
as-controller-board-status/functions/models.go
as-controller-board-status/functions/notify.go
as-controller-board-status/functions/notify_test.go
as-controller-board-status/functions/output.go
as-controller-board-status/functions/output_test.go
as-controller-board-status/go.mod
as-controller-board-status/go.sum
as-controller-board-status/main.go
as-controller-board-status/res/configuration.toml
as-controller-board-status/routes/controller_test.go

fix: refactored code to use custom configuration. This closes issue #44

---

ds-card-reader/device/device_test.go
ds-card-reader/device/physical_test.go
ds-card-reader/driver/driver.go
ds-card-reader/driver/driver_test.go

fix: ds-card-reader unit test to 80%+

---

docker-compose.ac.yml

fix: refactored  config overrides in docker compose yaml

---

as-vending/main.go
as-vending/routes/controller.go

so all app functions point to the same state

fix: change vendingState to a pointer

---

as-controller-board-status/functions/output.go
as-controller-board-status/functions/output_test.go
as-controller-board-status/routes/controller_test.go

fix: as-controller-board-status unit test

---

happy-path.sh

This script was added to make testing easier. Testing would not need to be ran manually

fix: added testing script

---

docs_src/automated-checkout-services/device_services.md
docs_src/automated-checkout-services/micro_services.md
docs_src/index.md
docs_src/phases/phase1.md

docs: update doc for edgex2.2 upgrade

---

res/device-mqtt/configuration.toml

add license header to device-mqtt configuration.toml file

---

docs_src/index.md

docs: update ubuntu version and go version

---

LICENSE
Makefile
as-controller-board-status/config/configuration.go
as-controller-board-status/functions/models.go
as-controller-board-status/functions/notify.go
as-vending/config/configuration.go
ds-cv-inference/mjpeg/mjpeg.go
happy-path.sh
ms-authentication/routes/gets.go
ms-inventory/routes/common.go
ms-inventory/routes/deletes.go
ms-inventory/routes/gets.go
ms-inventory/routes/sets.go
ms-inventory/routes/sets_test.go

fix: update license header

---

LICENSE
Makefile
as-controller-board-status/config/configuration.go
as-controller-board-status/functions/models.go
as-controller-board-status/functions/notify.go
as-vending/config/configuration.go
docs_src/index.md
happy-path.sh
ms-authentication/routes/gets.go
ms-inventory/routes/common.go
ms-inventory/routes/deletes.go
ms-inventory/routes/gets.go
ms-inventory/routes/sets.go
ms-inventory/routes/sets_test.go

Signed-off-by: Jim Wang (Intel) <yutsung.jim.wang@intel.com>

fix: out-merging with the current main branch to sync up

---

docs/configuration.html
docs/index.html
docs_src/configuration.md
docs_src/index.md

fix:doc docker compose wordings

---

ds-cv-inference/Dockerfile

Signed-off-by: Jim Wang (Intel) <yutsung.jim.wang@intel.com>

Hadolint fixes for cv inference

---

ds-cv-inference/Dockerfile
ds-cv-inference/entrypoint.sh
ds-cv-inference/go.mod
ds-cv-inference/go.sum
ds-cv-inference/inference/inference.go
ds-cv-inference/main.go
ds-cv-inference/mjpeg/mjpeg.go
ds-cv-inference/product-detection-0001/FP32/product-detection-0001.xml

Merging CV OPENVINO update into main

Merging 2022.2 into main branch

---

as-vending/Makefile
as-vending/routes/controller_test.go

fix: as-vending unit test

---

README.md

fix: Update github doc page

---

go.mod

fix: add top level gomod for microservice build

---

.github/PULL_REQUEST_TEMPLATE.md

fix: Correct link and wording in the PR template

---

Makefile
docker-compose.edgex.yml
res/mqtt/mosquitto.conf

closes #121
Migrated the EdgeX compose file to EdgeX 3.0 services
close: #**121**
Run `make run-edgex`
Verify all service, except device-mqtt, bootstrap without error

refactor: Migrate Edgex compose to 3.0

---

docker-compose.portainer.yml

build: Upgrade portianer to CE version

---

ds-cv-inference/mqtt/mqtt.go

close: #**issue_number**
build ds-cv-inference `cd ds-cv-inference` and run `make docker`

fix: Address Lenny's PR comments

---

smoke-test.sh

feat: Update test script for v3 endpoints

---

Makefile
docker-compose.av.yml

update naming and ensure everything comes up
close: #153
1. run `make docker`
2. run `make run`
3. ensure everything comes up

refactor: Fix naming of checkout-> vending and fix service names

---

as-controller-board-status/config/configuration.go
as-controller-board-status/functions/common_test.go
as-controller-board-status/functions/models.go
as-controller-board-status/functions/output.go
as-controller-board-status/functions/output_test.go
as-controller-board-status/main.go
as-controller-board-status/res/configuration.yaml
as-vending/functions/output.go

close: #142
- cd as-controller-board-status
- make docker
- make test

refactor: Use command client for as-controller-board-status to send commands instead of using REST calls.

---

.github/workflows/trivyimagescan.yaml
Makefile
docker-compose.av.yml
ms-authentication/Makefile

Cleans up AV Compose file. 
Cleans up Makefile clean target. 
Cleans up ms-authentication to use automated-vending instead of automated-checkout.
closes: #127
close: #**127**
- cd automated-vending
- Run `make docker`
- Run `make run`
- Check containers are up and running via Portainer.
- Run `make clean`

Edge x 3.0 update av cleanup env

---

README.md
docker-compose.physical.card-reader.yml
docker-compose.physical.controller-board.yml
ds-card-reader/device/config.go

closes: #143 
close: #**143**
Review text changes in files
- I didn't address the docs as that is being handled by #137

feat: update references of automated-checkout to automated-vending

---

ds-controller-board/res/devices/device-list.yaml
ds-cv-inference/Dockerfile
ds-cv-inference/entrypoint.sh
ds-cv-inference/go.mod
ds-cv-inference/go.sum
ds-cv-inference/inference/inference.go
ds-cv-inference/main.go
ds-cv-inference/product-detection-0001/FP32/product-detection-0001.xml
smoke-test.sh

refactor: Revert openvino

---

.github/workflows/scorecard.yaml

fix: Scorecard not uploading

---

.github/workflows/scorecard.yaml

fix: ossf scorecard

---

.github/workflows/scorecard.yaml

fix: update scorecard hash
